# Generated by Django 4.0.2 on 2022-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.CharField(default='https://www.akc.org/wp-content/uploads/2017/11/Labrador-Retriever-MP.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
