# Generated by Django 4.0.2 on 2022-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_visitors_date_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date of Walk')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='walker',
            field=models.ManyToManyField(to='main_app.Walker'),
        ),
    ]
